name: pipeline

on:
  - push

jobs:
  build:
    name: build
    runs-on: windows-2019
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: setup-haskell
        uses: actions/setup-haskell@v1
        with:
          ghc-version: 8.8.4

      - name: build
        run: |
          ghc -O -threaded -rtsopts Main.hs
          Main
